"""add status column to category_subjects

Revision ID: 59fcc9b6139f
Revises: 6ad2d2c1352d
Create Date: 2026-08-11 18:51:25.035749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fcc9b6139f'
down_revision: Union[str, Sequence[str], None] = '6ad2d2c1352d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category_subjects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_subjects', type_='unique')
    # ### end Alembic commands ###
